# Learn more at https://jupyterbook.org/customize/config.html
title: ''
author: The Xarray Community
copyright: '2022'
logo: images/logo.png
only_build_toc_files: true

# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  # NOTE: this announcement shows up on all pages
  announcement: 'ℹ️ The 2022 Xarray User Survey is out! Please take ~5 minutes to help improve Xarray! <a href="https://docs.google.com/forms/d/e/1FAIpQLSfnMd8UsC1XP1lPuFczl148VfpmwnFu4a0Z94odt1L6U0R0Pw/viewform">LINK</a>'
  home_page_in_navbar: false
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  # google_analytics_id: G-XXXXXXXXX

parse:
  # https://jupyterbook.org/content/content-blocks.html?highlight=myst%20substitution#define-substitutions-for-your-whole-book
  # https://jupyterbook.org/content/content-blocks.html#using-substitutions-in-links
  myst_substitutions:
    xarray_docs: https://xarray.dev
    xarray_repo: https://github.com/pydata/xarray
    xarray_forum: https://github.com/pydata/xarray/discussions
  myst_enable_extensions:
    # Defaults
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    # Extras
    - html_image

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'cache'
  allow_errors: false
  # Per-cell notebook execution limit (seconds)
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: 'https://mybinder.org'

# Information about where the book exists on the web
repository:
  url: 'https://github.com/xarray-contrib/xarray-tutorial'
  branch: main

# Bibliography
bibtex_bibfiles:
  - reference/references.bib
sphinx:
  config:
    bibtex_reference_style: author_year # or label, super, \supercite
  extra_extensions:
    - sphinx_exercise
    - sphinx_togglebutton
